- name: Install packages
  apt: 
    name: 
      - adobe-flashplugin
      - libreoffice
      - krita
      - libreoffice-l10n-fr
      - krita-l10n 
    state: present

- name: Remove unneeded packages
  apt: 
    name: 
      - tmux
      - mc 
    state: absent

- name: install snaps
  snap: 
    name: zoom-client
    state: present 
