- name: Install packages
  apt: 
    name: 
      - adobe-flashplugin
      - libreoffice
      - libreoffice-l10n-fr
      - remmina
      - remmina-plugin-rdp
    state: present

- name: Remove unneeded packages
  apt: 
    name: 
      - tmux
      - mc 
    state: absent

- name: install snaps
  snap: 
    name: zoom-client
    state: present 
