- name: Install packages
  apt: 
    name: 
      - htop
      - vim
      - adobe-flashplugin
    state: present

- name: Remove bloat
  apt: 
    name: ['mc','tmux']
    state: absent

- name: install snaps
  snap: 
    name: zoom-client
    state: present 
