- name: Install packages
  apt: name={{item}}
  with_items:
    - htop
  state: present

- name: Remove bloat
  apt: name={{item}}
  with_items:
    -mc
    -tmux
  state: absent

- name: install snaps
  community.general.snap: 
    name: zoom-client
    state: present 
