- name: Install packages
  apt: 
    name: 
      - libreoffice-l10n-fr
      - remmina
      - remmina-plugin-rdp
      state: present

- name: Remove packages 
  apt: 
    name: 
      - unattended-upgrades
    state: absent

- name: install snaps
  snap: 
    name: zoom-client
    state: present 
